### PR TITLE
Video playback demo

### LINKED ISSUE #17: Add VideoPlayback component
Similar to the `Camera` component, the ML model can be a nested component inside the `VideoPlayback` component in order to process the video in real time.

```
<VideoPlayback style={style} videoSource={videoSource}>
  <BlazePose
     .../>
</VideoPlayback>
```

### LINKED ISSUE #18: Support MoveNet
https://blog.tensorflow.org/2021/05/next-generation-pose-detection-with-movenet-and-tensorflowjs.html

### PR DESCRIPTION
**Pull request by henryouly**
- Add `VideoPlayback` React component (close #17) 
- Add `VideoPlaybackDemo` React app 
- Add `MoveNetLoader` (close #18)
- Add debug utils to display pose.

### CODE REVIEW

**Comment by wixette** [comment]
Quick feedback on two issues when I tested this pr:

## No start-https script is defined:

As described in README.md, 

```
# Or start demo server on https (for camera access in browser to work on localhost).
yarn start-https
```

But the command results in an error:

```
% yarn start-https
yarn run v1.22.10
error Command "start-https" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Although, I can still manually start an HTTPS instance with:

```
HTTPS=true npx react-scripts start
```

## CartoonMirror does not work on my machine

With or without HTTPS, the demo CartoonMirror does not work on my machine, while the other three demos work very well.

```shell
yarn install
yarn start   # or, for starting an HTTPS server, HTTPS=true npx react-scripts start
```

I've got the following error from Chrome:

```
[HMR] Waiting for update signal from WDS...
MeshoptDecoder.js:24 Warning: meshopt_decoder is using experimental SIMD support
pose_solution_simd_wasm_bin.js:9 I0905 11:03:34.957000       1 gl_context_webgl.cc:151] Successfully created a WebGL context with major version 3 and handle 3
pose_solution_simd_wasm_bin.js:9 I0905 11:03:34.962000       1 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)))
pose_solution_simd_wasm_bin.js:9 W0905 11:03:34.963000       1 gl_context.cc:807] OpenGL error checking is disabled
pose.js:53 Uncaught (in promise) TypeError: b.isProto is not a function
    at ka.h (pose.js:53)
    at V (pose.js:13)
    at ma.next (pose.js:14)
    at pose.js:25
    at new Promise (<anonymous>)
    at Y (pose.js:25)
    at Na (pose.js:53)
    at ka.h (pose.js:48)
    at V (pose.js:13)
    at ma.next (pose.js:14)
    at pose.js:25
    at new Promise (<anonymous>)
    at Y (pose.js:25)
    at Ma (pose.js:48)
    at Object.onResults (pose.js:55)
    at methodCaller_void_$Uint8BlobList$ (eval at new_ (pose_solution_simd_wasm_bin.js:9), <anonymous>:5:26)
    at __emval_call_void_method (pose_solution_simd_wasm_bin.js:9)
    at pose_solution_simd_wasm_bin.wasm:0x249a2
    at pose_solution_simd_wasm_bin.wasm:0x22b48
    at pose_solution_simd_wasm_bin.wasm:0x35dfea
    at pose_solution_simd_wasm_bin.wasm:0x378bf5
    at pose_solution_simd_wasm_bin.wasm:0x376af6
    at pose_solution_simd_wasm_bin.wasm:0x370ce3
    at pose_solution_simd_wasm_bin.wasm:0x189c6
    at pose_solution_simd_wasm_bin.wasm:0x13c86
    at SolutionWasm$send [as send] (eval at new_ (pose_solution_simd_wasm_bin.js:9), <anonymous>:9:1)
    at ka.h (pose.js:47)
    at V (pose.js:13)
    at ma.next (pose.js:14)
    at k (pose.js:25)
```

**Comment by henryouly** [comment]
Thanks for testing the PR.

re
> CartoonMirror does not work on my machine

I have run into this similar issue a few days ago and I believe it was a config issue on mediapipe solution path (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_simd_wasm_bin.js). I didn't make any fixes and today when I test it it is working, so I sent out the PR.

I'm on Microsoft Edge 91.0.864.48. Is it possible that issue is browser related? 

re
> No start-https script is defined

Thanks that's a good catch. I pick up the command from another project and have a local change to add `"start-https": "HTTPS=true react-scripts start"` when testing camera, but I figured that it seems I don't have to use it so I removed it without updating doc.

**Comment by wixette** [comment]
Interesting... The error of CartoonMirror is not browser-specific on my machine. I can repro it in Chrome, Safari, Firefox, and Edge.

* macOS Big Sur Version 11.5.2
  * Chrome Version 93.0.4577.63 (Official Build) (x86_64)
  * Safari Version 14.1.2 (16611.3.10.1.6)
  * Firefox 91.0.2 (64-bit)
  * Edge Version 93.0.961.38 (Official build) (x86_64)

All the browsers reported the common error message "TypeError: b.isProto is not a function".

**Review by wixette — APPROVED** [review]
Although there is still an error being reproduced, I've gone through the PR and found the code itself is clear, in good style.

I am approving the PR. Please feel free to merge it to `main` if you think it's good to do that. You can keep working to locate the root cause of the error.

**Comment by henryouly** [comment]
Thanks. I submitted #25 to track the issue.

**Pull request merged**
